### ISSUE TITLE
Compatability with Monterey

### ISSUE THREAD

**Issue by mcwsc3** [dieskim/FilevaultReboot#1]
Would it be possible to get this working on 12.6.x? This has been very handy for me on Ventura systems I administer, but I'd love to use it on Monterey machines, as well.

**Comment by dieskim** [comment]
Hi, sorry I missed this. This is using [menubarextra](https://developer.apple.com/documentation/swiftui/menubarextra) for the UI, and it’s only supported on Ventura. To make it work on Monterey would require a bit of work to recode the UI but the bulk of the logic to actually make it work would stay the same.

**Comment by dieskim** [comment]
added https://github.com/dieskim/FilevaultReboot/releases/download/v1.1.0/FilevaultReboot-Pre-Ventura.dmg
